// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using servicio.api.reglamento.Core.Context;

#nullable disable

namespace servicio.api.reglamento.Migrations
{
    [DbContext(typeof(ReglamentoContext))]
    partial class ReglamentoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("servicio.api.reglamento.Core.Entity.ReglamentoEntity", b =>
                {
                    b.Property<Guid>("ReglamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReglamentoId");

                    b.ToTable("Reglamento", (string)null);

                    b.HasData(
                        new
                        {
                            ReglamentoId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136db03"),
                            Descripcion = "Reglamento de ligra masculina de futbol lpf",
                            DocumentoUrl = "https://lpf.com.pa/wp-content/uploads/2023/01/REGLAMENTO-DE-COMPETENCIA-LPF-2023.pdf",
                            Estado = 0,
                            FechaCreado = new DateTime(2023, 4, 17, 11, 39, 37, 290, DateTimeKind.Local).AddTicks(8104),
                            ImagenUrl = "https://lpf.com.pa/wp-content/uploads/2023/01/REGLAMENTO-DE-COMPETENCIA-LPF-2023-791x1024.webp",
                            Tipo = 0,
                            Titulo = "LPF"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
